package com.hyperscope.android.data

import kotlinx.serialization.Serializable

/**
 * A monitored node = a hyper-node HTTP server the phone connects to directly.
 * No central panel is involved: the phone IS the panel.
 */
@Serializable
data class NodeConfig(
    val name: String = "",
    val addr: String = "",
    val port: Int = 5000,
    val key: String = "",
)

/** Node [/system] payload (field names match hyper-node metrics.rs). */
@Serializable
data class NodeSystem(
    val node_name: String = "",
    val version: String = "",
    val kernel: String = "",
    val cpu: Double = 0.0,
    val cpu_temp: String = "N/A",
    val cpu_temp_raw: Double? = null,
    val gpu_temp: String = "N/A",
    val gpu_temp_raw: Double? = null,
    val cpu_cores: Int = 0,
    val cpu_mhz: String = "",
    val mem_total: String = "",
    val mem_used: String = "",
    val mem_percent: Double = 0.0,
    val disk_total: String = "",
    val disk_used: String = "",
    val disk_percent: Double = 0.0,
    val loadavg: String = "",
    val uptime: String = "",
    val processes: Int = 0,
)

@Serializable
data class DiskInfo(val name: String = "", val total: String = "", val used: String = "", val percent: Double = 0.0)

@Serializable
data class DisksResponse(val disks: List<DiskInfo> = emptyList())

@Serializable
data class ProcInfo(
    val pid: Long = 0,
    val name: String = "",
    val cpu: Double = 0.0,
    val rss_mb: Double = 0.0,
    val state: String = "",
)

@Serializable
data class ProcessesResponse(val processes: List<ProcInfo> = emptyList())

@Serializable
data class ContainerInfo(val name: String = "", val running: Boolean = false, val image: String = "", val state: String = "")

@Serializable
data class DockerResponse(val containers: List<ContainerInfo> = emptyList())

/** A local notification (generated by the app from node state changes/alerts). */
data class NotifItem(
    val time: String = "",
    val node: String = "",
    val kind: String = "info", // online | offline | alert
    val msg: String = "",
)

/** Aggregated state for one node, refreshed periodically. */
data class NodeView(
    val config: NodeConfig,
    val system: NodeSystem? = null,
    val disks: List<DiskInfo> = emptyList(),
    val processes: List<ProcInfo> = emptyList(),
    val online: Boolean = false,
    val error: String? = null,
    /**
     * Monotonic refresh counter. Bumped on every poll so the StateFlow value
     * always differs (data-class equals would otherwise suppress notifications
     * when consecutive polls produce identical results, leaving the UI stale).
     */
    val seq: Long = 0,
)
