package com.hyperscope.android.data

import kotlinx.serialization.Serializable

/**
 * A monitored node = a hyper-node HTTP(S) server the phone connects to directly.
 * The phone is the panel; no central server is involved.
 */
@Serializable
data class NodeConfig(
    val name: String = "",
    val addr: String = "",
    val port: Int = 8686,
    val key: String = "",
    /** True when the node serves HTTPS (TLS mode); cert fingerprint is pinned. */
    val tls: Boolean = false,
    /** SHA256 certificate fingerprint (hex, no colons) for pinning when tls=true. */
    val certFp: String = "",
    /** Group/label for organising the node list (e.g. "office", "hk"). */
    val group: String = "",
    /** Webhook URL for alert push (ntfy/Bark/Server Chan style). Empty = off. */
    val webhook: String = "",
    /** Per-node alert thresholds; null = use defaults (90/90/90/85). */
    val alertCpu: Double? = null,
    val alertMem: Double? = null,
    val alertDisk: Double? = null,
    val alertTemp: Double? = null,
    /** True when the node runs in relay mode (no listening port): the app
     * queries the node's hyper-relay for a temporary address before fetching. */
    val push: Boolean = true,
)

/** Node [/system] payload (field names match hyper-node metrics.rs). */
@Serializable
data class NodeSystem(
    val node_name: String = "",
    val version: String = "",
    val kernel: String = "",
    val cpu: Double = 0.0,
    val cpu_temp: String = "N/A",
    val cpu_temp_raw: Double? = null,
    val gpu_temp: String = "N/A",
    val gpu_temp_raw: Double? = null,
    val cpu_cores: Int = 0,
    val cpu_mhz: String = "",
    val mem_total: String = "",
    val mem_used: String = "",
    val mem_percent: Double = 0.0,
    val disk_total: String = "",
    val disk_used: String = "",
    val disk_percent: Double = 0.0,
    val loadavg: String = "",
    val uptime: String = "",
    val processes: Int = 0,
)

@Serializable
data class DiskInfo(val name: String = "", val total: String = "", val used: String = "", val percent: Double = 0.0)

@Serializable
data class DisksResponse(val disks: List<DiskInfo> = emptyList())

@Serializable
data class ProcInfo(
    val pid: Long = 0,
    val name: String = "",
    val cpu: Double = 0.0,
    val rss_mb: Double = 0.0,
    val state: String = "",
)

@Serializable
data class ProcessesResponse(val processes: List<ProcInfo> = emptyList())

@Serializable
data class ContainerInfo(val name: String = "", val running: Boolean = false, val image: String = "", val state: String = "")

@Serializable
data class DockerResponse(val containers: List<ContainerInfo> = emptyList())

/** Network interface speeds from /traffic. */
@Serializable
data class TrafficInfo(
    val iface: String = "",
    val speed_rx: Double = 0.0,
    val speed_tx: Double = 0.0,
    val speed_rx_str: String = "0 B/s",
    val speed_tx_str: String = "0 B/s",
)

/** Disk I/O + TCP from /io. */
@Serializable
data class IoInfo(
    val device: String = "",
    val disk_read_mbs: Double = 0.0,
    val disk_write_mbs: Double = 0.0,
    val tcp_conns: Int = 0,
)

/** Rolling cpu/mem samples for the trend chart. */
@Serializable
data class TrendHistory(
    val cpu: List<Double> = emptyList(),
    val mem: List<Double> = emptyList(),
)

/** Rolling network speed samples (rx/tx bytes per second) for the speed card. */
@Serializable
data class SpeedHistory(
    val rx: List<Double> = emptyList(),
    val tx: List<Double> = emptyList(),
)

/** A local notification (generated by the app from node state changes/alerts). */
data class NotifItem(
    val time: String = "",
    val node: String = "",
    val kind: String = "alert",
    val msg: String = "",
)

/** Bundle of one node's parallel refresh results (used to avoid nested Pairs). */
data class NodeRefreshResult(
    val sys: NodeSystem?,
    val disks: List<DiskInfo>,
    val procs: List<ProcInfo>,
    val dock: DockerResponse,
)

/** Event history entry (node up/down + alert triggers), mirroring the panel's events. */
data class EventItem(
    val time: String = "",
    val node: String = "",
    val kind: String = "", // "up" | "down" | "alert"
    val msg: String = "",
)

/** Aggregated state for one node, refreshed periodically. */
@Serializable
data class NodeView(
    val config: NodeConfig,
    val system: NodeSystem? = null,
    val disks: List<DiskInfo> = emptyList(),
    val processes: List<ProcInfo> = emptyList(),
    val docker: DockerResponse = DockerResponse(),
    val online: Boolean = false,
    val error: String? = null,
    /**
     * True while a refresh is in flight and we have no data yet (first poll or
     * return from background) — the UI shows "fetching" instead of an error.
     */
    val loading: Boolean = false,
    /**
     * Monotonic refresh counter. Bumped on every poll so the StateFlow value
     * always differs (data-class equals would otherwise suppress notifications
     * when consecutive polls produce identical results, leaving the UI stale).
     */
    val seq: Long = 0,
    val traffic: TrafficInfo? = null,
    val io: IoInfo? = null,
)
